### PR TITLE
feat(templates): make template files exchangeable

### PR DESCRIPTION
**Pull request by lask79**
I would like to be able override some of the settings in the template files. I changed from hardcoded template file names to an exchangeable template file variable.

### CODE REVIEW

**Comment by juju4** [comment]
LGTM on templating but there are other changes mixed (linting or related) which should be in a separate commit. please update. thanks

**Comment by lask79** [comment]
I merged your last ansible-lint fixes. now it should be fine

**Comment by juju4** [comment]
Thanks but strangely, they appear in your PR where it should not as already in tree
also, please remove changes which are not related to the template. as said, should be a different PR and not sure needed. for example, why simple vs double quotes?

**Comment by lask79** [comment]
now it should be fine :-)

**Pull request merged**
