### PR TITLE
Replace key generation

### LINKED ISSUE #12: Fetch privatekey file to orchestrator fails on Ubuntu 22.04
When running on Ubuntu 22.04 retrieving the secret key fails.
```
failed: [example] (item=/etc/pki/gpg/duply/root.priv) => {"ansible_loop_var": "item", "changed": false, "item": "/etc/pki/gpg/duply/root.priv", "msg": "the remote file does not exist, not transferring, ignored"}
```

This appears to be because the private key is no longer available in GPG 2.1 (https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html).

Looking through the code it appears 31423de47ddd4c639cc167fce65fd6c71386bf5b from 2016 was probably fixing this issue for key importing (though its not explicit in the commit message).

Given that Ubuntu < 16.04 and RHEL <7 are out of mainline support; is it time to remove that parameter from the role and the option from gen-key-script?

### PR DESCRIPTION
**Pull request by goetzk**
Replace GPG key generation and exporting code in an attempt to improve
robustness.
This PR is built on #13 so would ideally be merged after it.

* Adds --batch to several tasks so GPG won't request input.
* Changes to --quick-generate-key with CLI options instead of --gen-key with
  configuration file.
* Removes importing generated keys; no longer required with --quick-generate-key
* Moved public key export to 'command' module instead of 'shell' by specifying
  --output parameter.
* Add exporting of private key which was lost with the introduction of GPG
  ephemeral homes, closes https://github.com/juju4/ansible-gpgkey_generate/issues/12 .

Sorry this commit message is a bit terse, the original went missing during rebase.

### CODE REVIEW

**Comment by juju4** [comment]
let's review after the smaller two other ones.
approving CI.

**Comment by juju4** [comment]
Other PR were merged. Can you fix conflicts and lint and will review after?

**Comment by goetzk** [comment]
There are a couple of failures left, one of which seems serious.

The first is a whitespace linting issue - for the life of me I can't figure out how I'm supposed to improve it. 
```
jinja[spacing]: Jinja2 spacing could be improved: gpg --batch --homedir "{{ gpg_home }}/.gnupg"
  --passphrase-file "{{ gpg_home + '/' + gpg_passphrase_file }}"
  --quick-generate-key "{{ gpg_realname }} {{ gpg_useremail }}"
  future-default default "{{ gpg_expire |default('10y') }}"
 -> gpg --batch --homedir "{{ gpg_home }}/.gnupg"
  --passphrase-file "{{ gpg_home + '/' + gpg_passphrase_file }}"
  --quick-generate-key "{{ gpg_realname }} {{ gpg_useremail }}"
  future-default default "{{ gpg_expire | default('10y') }}"
```

The second is on the rocky derived systems, and something to do with contacting the agent. I will need to come back to this as I don't currently have a RH based system to test against. Although I hadn't seen it before opening this PR I have also seen a similar error on Ubuntu systems so it might not be an OS specific issue and there might be a common cause.
```
  fatal: [instance]: FAILED! => {"changed": true, "cmd": ["gpg", "--batch", "--homedir", "/home/myuser/.gnupg", "--passphrase-file", "/home/myuser/passphrase.key", "--output", "/home/myuser/root.priv", "--armor", "--export-secret-key", "root@localhost"], "delta": "0:00:00.023860", "end": "2023-10-08 03:06:25.735819", "msg": "non-zero return code", "rc": 2, "start": "2023-10-08 03:06:25.711959", "stderr": "gpg: key 332A1E064645E5C02400F68C06BA60549977B1C8: error receiving key from agent: No pinentry - skipped\ngpg: key 614B0BAD995F934B7234FB534DC611D646C53F87: error receiving key from agent: No pinentry - skipped\ngpg: WARNING: nothing exported", "stderr_lines": ["gpg: key 332A1E064645E5C02400F68C06BA60549977B1C8: error receiving key from agent: No pinentry - skipped", "gpg: key 614B0BAD995F934B7234FB534DC611D646C53F87: error receiving key from agent: No pinentry - skipped", "gpg: WARNING: nothing exported"], "stdout": "", "stdout_lines": []}
```

The third is a failure on Centos 7 as it doesn't have `--quick-generate-key`. Quick generate key was added in 2014 (https://github.com/gpg/gnupg/commit/ea186540db5b418bc6f6e5ca90337672c9981c88) and is present since GPG 2.1.
```
  fatal: [instance]: FAILED! => {"changed": true, "cmd": ["gpg", "--batch", "--homedir", "/home/myuser/.gnupg", "--passphrase-file", "/home/myuser/passphrase.key", "--quick-generate-key", "GPG Ansible user root@localhost", "future-default", "default", "360"], "delta": "0:00:00.639075", "end": "2023-10-08 03:06:27.733315", "msg": "non-zero return code", "rc": 2, "start": "2023-10-08 03:06:27.094240", "stderr": "gpg: invalid option \"--quick-generate-key\"", "stderr_lines": ["gpg: invalid option \"--quick-generate-key\""], "stdout": "", "stdout_lines": []}
```

C7 has another 8 months until EOL https://www.redhat.com/en/topics/linux/centos-linux-eol so depending on your compatibility requirements this might be a problem.

**Comment by goetzk** [comment]
ok, those pushes resolves two issues - the unexpected failure for Rocky and the lint issue ('default' needed a space in front of it).
The only question outstanding is that of RHEL7 support.  The change to requiring GPG 2.1 (which comes in with this branch) means the GPG native to RHEL 7 is not sufficient - a backport has to be sourced on those systems.

**Comment by juju4** [comment]
All good.
I'm fine with ignoring RHEL7. To be removed soon anyway.

**Comment by goetzk** [comment]
Thanks!

**Pull request merged**
